CREATE TABLE issue273 (
    id bigint not null primary key,
    data text
);
insert into issue273 (id, data) values (1, 'this is a test');
create index idxissue273 on issue273 using zombodb ((issue273.*));
begin;
select txid_current() is not null;  -- burn current xid
 ?column? 
----------
 t
(1 row)

savepoint foo;
update issue273 set id = id where id = 1;  -- gets next xid value
commit; -- results in ERROR because "next xid value" doesn't exist in events' list of aborted xids.
ERROR:  unexpected http response code from remote server.  code=400, response={"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[OxNDdMz][127.0.0.1:9300][indices:data/write/update[s]]"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"runtime error","script_stack":[],"script":"ctx._source.zdb_aborted_xids.remove(ctx._source.zdb_aborted_xids.indexOf(params.XID));","lang":"painless","caused_by":{"type":"array_index_out_of_bounds_exception","reason":null}}},"status":400}
DROP TABLE issue273;
